(function(){

  /* =====================================================================
   * DATA: cameras, lenses, gear, shooting types
   * =================================================================== */

  var CAMERAS = {
    "Sony": ["Alpha 1 II","Alpha 9 III","Alpha 7R V","Alpha 7S III","Alpha 7 IV","Alpha 7C II","Alpha 6700","FX3 Cinema Line","FX30 Cinema Line","ZV-E10 II"],
    "Canon": ["EOS R1","EOS R5 Mark II","EOS R6 Mark II","EOS R3","EOS R8","EOS R7","EOS R10","EOS R50","EOS 5D Mark IV","PowerShot G7 X Mark III"],
    "Nikon": ["Z9","Z8","Z6 III","Z5 II","Zf","Z50 II","Z30","D850"],
    "Fujifilm": ["GFX100 II","X-H2","X-H2S","X-T5","X-T50","X-S20","X100VI"],
    "Panasonic (Lumix)": ["S1R II","S1H","S5 IIX","GH6","G9 II"],
    "OM System": ["OM-1 II","OM-3","OM-5 II","E-M1 III"],
    "Leica": ["SL3-S","Q3","M11"],
    "Hasselblad": ["X2D 100C","907X"],
    "Pentax": ["K-1 II","K-3 III","645Z"],
    "Ricoh": ["GR III","GR IIIx"],
    "Sigma": ["BF","fp L"],
    "Blackmagic Design": ["Pocket Cinema Camera 6K Pro","Pocket Cinema Camera 6K G2","URSA Mini Pro 12K"],
    "GoPro": ["HERO13 Black","HERO12 Black","HERO11 Black Mini","MAX"],
    "DJI": ["Osmo Pocket 3","Osmo Action 5 Pro","Ronin 4D","Mavic 3 Pro (drone)","Mini 4 Pro (drone)"],
    "Apple": ["iPhone 18 Pro Max","iPhone 18 Pro","iPhone 17 Pro Max","iPhone 17 Pro","iPhone 17e","iPhone 16 Pro Max"],
    "Samsung": ["Galaxy S26 Ultra","Galaxy S26+","Galaxy S26","Galaxy S26 FE","Galaxy S25 Ultra"],
    "Google": ["Pixel 11 Pro XL","Pixel 11 Pro","Pixel 11","Pixel 10 Pro"],
    "OnePlus": ["OnePlus 13","OnePlus 13R","OnePlus Open"],
    "Xiaomi": ["Xiaomi 14 Ultra","Xiaomi 14"],
    "Oppo": ["Find X8 Pro"],
    "Vivo": ["X200 Pro"],
    "Motorola": ["Edge Plus","Razr Plus"],
    "Other": []
  };

  var LENSES = ["Kit zoom (18-55mm)","Wide-angle (10-24mm)","Standard zoom (24-70mm)","Telephoto zoom (70-200mm)","Super telephoto (150-600mm)","50mm prime","85mm prime","Macro lens","Fisheye lens","Cinema prime","Built-in phone lens"];

  var GEAR = ["Tripod","Gimbal / stabilizer","ND filters","Polarizer (CPL)","External flash","LED light","Reflector","Lavalier mic","Drone","Slider / dolly"];

  var STYLES = {
    photo: ["Portrait","Landscape","Macro / close-up","Astrophotography","Sports / action","Street / candid","Wildlife","Product / studio","Long exposure","Night / low light"],
    video: ["Cinematic","Slow motion","Timelapse","Hyperlapse","Vlog / talking head","Action / sports","Low light / night","Interview","Aerial / drone","Music video / B-roll"]
  };

  /* =====================================================================
   * DATA: per-style baseline settings (standard exposure-triangle rules
   * of thumb, computed locally -- not a light-meter reading of your
   * actual scene).
   * =================================================================== */

  var PHOTO_DATA = {
    "Portrait": { aperture:"f/1.8 \u2013 f/2.8", shutter:"1/125s or faster", iso:"100\u2013400 outdoors, 400\u20131600 indoors", wb:"Auto, or Shade for warmer skin tones", focus:"Single-shot AF on the near eye", note:"Meter for the face, not the background.", idealLens:["85mm prime","50mm prime","Standard zoom (24-70mm)"], wantsTripod:false, wantsND:false, tips:["Focus on the eye closest to the camera \u2014 everything else reads off that.","Open the aperture as wide as your lens allows for background separation.","Watch the edges of the frame for clutter or bright spots that pull attention."], summary:"Keep the aperture wide, lock focus on the eye, and let the background fall away." },
    "Landscape": { aperture:"f/8 \u2013 f/11", shutter:"1/125s handheld, or several seconds on a tripod", iso:"100 (base ISO)", wb:"Daylight, or Auto", focus:"Manual, focused about a third into the scene", note:"Use a 2-second timer or remote release so you're not touching the camera at the moment of exposure.", idealLens:["Wide-angle (10-24mm)","Kit zoom (18-55mm)"], wantsTripod:true, wantsND:true, tips:["Shoot during golden hour for softer light and longer shadows.","f/8\u2013f/11 is the sharpest range on most lenses \u2014 don't go narrower than you need.","A polarizer cuts glare and deepens skies if the sun's off to one side."], summary:"Stop down for depth, steady the camera, and let the light do the rest." },
    "Macro / close-up": { aperture:"f/8 \u2013 f/16", shutter:"1/200s+ handheld, slower on a tripod or with flash", iso:"200\u2013800", wb:"Auto", focus:"Manual focus \u2014 autofocus hunts at macro distances", note:"Depth of field is razor-thin up close; a small aperture buys a little more of it.", idealLens:["Macro lens","Telephoto zoom (70-200mm)"], wantsTripod:true, wantsND:false, tips:["Focus by rocking slightly forward and back once you're close, rather than turning the ring.","A diffused flash or reflector fills the shadow you'll otherwise cast on the subject.","Even small vibrations show at this magnification \u2014 a tripod or fast shutter helps."], summary:"Stop down for depth, focus manually, and control your light source carefully." },
    "Astrophotography": { aperture:"As wide as your lens goes (f/1.4 \u2013 f/2.8)", shutter:"10\u201325s (roughly 500 \u00f7 focal length, before stars trail)", iso:"1600\u20136400", wb:"3200\u20134000K, or Auto", focus:"Manual focus to infinity, checked by zooming in on a bright star in live view", note:"Turn off image stabilization once the camera's on a tripod \u2014 it can introduce blur on a static shot.", idealLens:["Wide-angle (10-24mm)"], wantsTripod:true, wantsND:false, tips:["Shoot RAW \u2014 you'll want the latitude to pull shadows in post.","Get away from light pollution if you can; it matters more than any setting here.","A 2-second timer or remote release avoids shake from pressing the shutter."], summary:"Widest aperture, longest shutter before trailing, and manual focus locked to infinity." },
    "Sports / action": { aperture:"f/2.8 \u2013 f/5.6", shutter:"1/1000s or faster", iso:"Auto (400\u20133200 depending on light)", wb:"Auto", focus:"Continuous AF (AF-C) with subject tracking, burst drive mode", note:"Switch the drive mode to high-speed burst so you're not relying on a single click's timing.", idealLens:["Telephoto zoom (70-200mm)","Super telephoto (150-600mm)"], wantsTripod:false, wantsND:false, tips:["Pre-focus on where the action will happen and let tracking take over from there.","Shoot in bursts through the peak of the action rather than single frames.","A monopod saves your arms on a long lens without losing much stability."], summary:"Fast shutter, continuous tracking, and burst mode to catch the peak of the action." },
    "Street / candid": { aperture:"f/5.6 \u2013 f/8", shutter:"1/250s or faster", iso:"Auto (100\u20131600)", wb:"Auto", focus:"Zone focus, or wide-area AF-C", note:"Pre-set your exposure so the camera's ready the instant something happens.", idealLens:["Wide-angle (10-24mm)","Standard zoom (24-70mm)"], wantsTripod:false, wantsND:false, tips:["Zone-focus at a set distance so you can shoot without waiting on autofocus.","Look for the light and the background first, then wait for a subject to walk into it.","Keep settings simple enough that you can react in a second or two."], summary:"Stay ready with zone focus and a fast-enough shutter so you never miss the moment." },
    "Wildlife": { aperture:"As wide as your telephoto allows (f/4 \u2013 f/6.3)", shutter:"1/1000\u20131/2000s", iso:"Auto, raised as needed for shade or foliage", wb:"Auto", focus:"AF-C with animal-eye tracking if your camera has it", note:"A bean bag or monopod steadies a long lens far better than hand-holding alone.", idealLens:["Super telephoto (150-600mm)","Telephoto zoom (70-200mm)"], wantsTripod:true, wantsND:false, tips:["Shoot in bursts \u2014 animal behavior turns in a fraction of a second.","Focus on the eye; a sharp eye forgives a lot elsewhere in the frame.","Patience and knowing the animal's habits beats chasing it every time."], summary:"Fast shutter, tracking autofocus, and the patience to wait for the moment." },
    "Product / studio": { aperture:"f/8 \u2013 f/11", shutter:"1/125s (typical flash sync)", iso:"100 (base ISO)", wb:"Match your lights \u2014 use a custom white balance if you can", focus:"Manual focus, or single-AF with focus peaking", note:"A grey card or color checker keeps color consistent across a whole shoot.", idealLens:["Macro lens","50mm prime","Standard zoom (24-70mm)"], wantsTripod:true, wantsND:false, tips:["Diffuse your light source \u2014 direct light on glossy products creates hot reflections.","Lock the camera on a tripod so composition stays identical across a whole set.","Shoot a grey card once under your lighting to nail white balance in post."], summary:"Controlled light, a locked-off tripod, and a small aperture for edge-to-edge sharpness." },
    "Long exposure": { aperture:"f/8 \u2013 f/16", shutter:"Several seconds to a few minutes, depending on the effect", iso:"100 (base ISO)", wb:"Daylight, or Auto", focus:"Manual \u2014 focus before attaching a dark ND filter, autofocus won't see through it", note:"A strong ND filter is what lets you shoot long exposures in daylight at all.", idealLens:["Wide-angle (10-24mm)"], wantsTripod:true, wantsND:true, tips:["Cover the viewfinder eyepiece \u2014 light can leak in during a long exposure.","Start around 1\u20134 seconds for silky water, 30s+ for streaking clouds.","Use a remote release or the camera's timer so you're not touching it mid-exposure."], summary:"Lock it down, filter the light, and let the shutter stay open for the effect you're after." },
    "Night / low light": { aperture:"As wide as your lens allows (f/1.4 \u2013 f/2.8)", shutter:"1/30\u20131/60s handheld, longer on a tripod", iso:"1600\u20136400", wb:"Auto, or Tungsten under artificial light", focus:"Single AF with an assist light, or manual", note:"A little extra ISO usually looks better than a blurry shot from too slow a shutter.", idealLens:["50mm prime","85mm prime"], wantsTripod:true, wantsND:false, tips:["Brace against something solid if you don't have a tripod on you.","Shoot RAW \u2014 it gives you real room to clean up noise afterward.","Don't be afraid of ISO \u2014 a sharp, grainy shot beats a smooth, blurry one."], summary:"Open the aperture, accept some ISO, and stabilize however you can." }
  };

  var VIDEO_DATA = {
    "Cinematic": { aperture:"f/2.8 \u2013 f/4", shutter:"1/50s (180-degree rule at 24fps)", iso:"Base ISO of your camera (usually 100\u2013800)", fps:"24fps", wb:"Match the scene \u2014 5600K daylight or 3200K tungsten", focus:"Manual focus, or smooth AF-C", note:"Use ND filters to hold that shutter speed in bright daylight instead of stopping the aperture down.", idealLens:["Cinema prime","Standard zoom (24-70mm)"], wantsTripod:false, wantsND:true, wantsMic:false, tips:["The 180-degree rule (shutter \u2248 double your frame rate) is what gives motion its natural blur.","Keep white balance locked across a scene so cuts don't shift in color.","A gimbal or slider adds production value even to simple moves."], summary:"Hold the 180-degree rule, lock your white balance, and let the movement stay deliberate." },
    "Slow motion": { aperture:"f/4 \u2013 f/8 (use ND to get there in bright light)", shutter:"1/250 \u2013 1/500s for crisp per-frame detail", iso:"As low as the light allows", fps:"120fps (240fps for extreme slow-mo)", wb:"Match the scene", focus:"AF-C tracking for moving subjects", note:"High frame rates need a lot of light per frame \u2014 shoot in bright conditions or add light.", idealLens:["Telephoto zoom (70-200mm)","Standard zoom (24-70mm)"], wantsTripod:false, wantsND:true, wantsMic:false, tips:["Bigger, more deliberate motion reads much better once it's slowed down.","120fps into a 24fps timeline gives 5x slow motion \u2014 plan that math before you shoot.","Bring more light than you think you need \u2014 high fps eats it fast."], summary:"Shoot with plenty of light, keep the motion bold, and let the frame rate do the drama." },
    "Timelapse": { aperture:"f/8 \u2013 f/11", shutter:"Interval: 1 frame every 2\u20135s for clouds/people, 10\u201330s for slower change", iso:"100 (base ISO)", fps:"24\u201330fps playback", wb:"Lock a manual white balance so frames don't shift", focus:"Manual focus, locked", note:"Total frames needed = final clip length in seconds \u00d7 playback fps \u2014 work backward from that to set your interval.", idealLens:["Wide-angle (10-24mm)"], wantsTripod:true, wantsND:true, wantsMic:false, tips:["Lock exposure and white balance manually \u2014 auto modes cause visible flicker between frames.","An intervalometer (built-in or external) is essentially required past a few minutes.","Faster-moving subjects (traffic, crowds) want a shorter interval than slow ones (clouds, stars)."], summary:"Lock every setting manually, pick an interval to match how fast the scene changes, and let it run." },
    "Hyperlapse": { aperture:"f/8 \u2013 f/11", shutter:"1/50\u20131/100s per frame", iso:"100\u2013400", fps:"24\u201330fps playback", wb:"Locked / manual", focus:"Manual, or locked between moves", note:"Unlike a timelapse, you physically move between each frame \u2014 keep the steps even.", idealLens:["Wide-angle (10-24mm)"], wantsTripod:false, wantsND:false, wantsMic:false, tips:["Keep your steps and framing consistent \u2014 uneven spacing shows up as a jerky result.","A dedicated hyperlapse app or a gimbal helps smooth the motion between shots.","Lock exposure so the scene doesn't flicker brighter and darker as you move."], summary:"Move in even, deliberate steps and keep exposure locked from the first frame to the last." },
    "Vlog / talking head": { aperture:"f/2.8 \u2013 f/4", shutter:"1/60s (180-degree rule at 30fps)", iso:"As needed for the room", fps:"30fps", wb:"Match your lighting, or set a custom white balance", focus:"AF-C with face or eye tracking", note:"Audio quality matters more than video quality here \u2014 prioritize the mic.", idealLens:["Standard zoom (24-70mm)","Wide-angle (10-24mm)"], wantsTripod:true, wantsND:false, wantsMic:true, tips:["A lav or shotgun mic close to you will outperform the camera's built-in mic every time.","One key light and a fill (even a reflector) evens out harsh shadows on the face.","Leave a little headroom in the frame, but not so much you look small."], summary:"Prioritize clean audio and even face lighting \u2014 the video settings are the easy part." },
    "Action / sports": { aperture:"f/2.8 \u2013 f/5.6", shutter:"1/120 \u2013 1/250s (a bit faster than the 180-degree rule, for crisper action)", iso:"Auto", fps:"60fps", wb:"Auto", focus:"Wide-area AF-C tracking", note:"Shooting at 60fps even for normal-speed footage gives you the option to slow it down later.", idealLens:["Telephoto zoom (70-200mm)"], wantsTripod:false, wantsND:false, wantsMic:false, tips:["Follow the subject with the camera rather than zooming to keep up.","A gimbal turns running-and-gunning footage from shaky to usable.","Frame a little loose \u2014 fast subjects drift out of tight crops."], summary:"Shoot a little faster than the rule of thumb calls for, track wide, and follow the motion." },
    "Low light / night": { aperture:"As wide as your lens allows (f/1.4 \u2013 f/2.8)", shutter:"1/24 \u2013 1/50s", iso:"3200\u201312800 depending on your camera's low-light performance", fps:"24fps", wb:"Auto, or Tungsten under artificial light", focus:"Manual \u2014 autofocus struggles in the dark", note:"A camera with strong high-ISO performance matters more here than almost any setting choice.", idealLens:["50mm prime","85mm prime"], wantsTripod:true, wantsND:false, wantsMic:false, tips:["Add a practical light into the scene wherever you can \u2014 a lamp, a phone screen, string lights.","Stabilize however possible \u2014 a slower shutter shows every bit of handheld movement.","Don't be afraid to break the 180-degree rule and go slower if you need the light."], summary:"Open up, accept the ISO you need, and add any practical light you can find." },
    "Interview": { aperture:"f/2.8 \u2013 f/4", shutter:"1/50 \u2013 1/60s", iso:"As low as the lighting allows", fps:"24\u201330fps", wb:"Custom white balance for your key light setup", focus:"Manual focus, locked once framed", note:"A simple 3-point lighting setup (key, fill, back) does more for the shot than any camera setting.", idealLens:["85mm prime","Standard zoom (24-70mm)"], wantsTripod:true, wantsND:false, wantsMic:true, tips:["Get the mic as close to the subject as you can, even if it means keeping it carefully out of frame.","Leave a bit of look-room in the direction the subject is facing.","Lock focus once they're framed \u2014 most interview subjects don't move much."], summary:"Light it properly, mic it closely, and lock the frame down \u2014 the camera does the rest." },
    "Aerial / drone": { aperture:"Often fixed on drones \u2014 control exposure with ND filters and shutter instead", shutter:"1/50 \u2013 1/60s (180-degree rule)", iso:"100\u2013200", fps:"24\u201330fps", wb:"Auto, or locked custom", focus:"Usually fixed or hyperfocal on drone cameras", note:"Match your ND filter strength to the light so you can hold the correct shutter speed.", idealLens:["Built-in phone lens"], wantsTripod:false, wantsND:true, wantsMic:false, tips:["Fly slow and smooth \u2014 cinematic aerials are about restraint, not speed.","Check local drone regulations and no-fly zones before you launch.","ND filters matched to conditions do more for footage quality than almost any camera setting here."], summary:"Filter the light to hold your shutter speed, and fly slower than feels natural." },
    "Music video / B-roll": { aperture:"f/1.8 \u2013 f/2.8", shutter:"1/50s (or break the rule intentionally for a stylized strobe look)", iso:"As needed", fps:"24fps (or 60fps for slow-motion cutaways)", wb:"Stylized \u2014 lean warm or cool to match the mood", focus:"AF-C, or manual depending on the move", note:"Gather more shot variety (wide, medium, close, detail) than feels necessary \u2014 cheap now, valuable in the edit.", idealLens:["Cinema prime","Telephoto zoom (70-200mm)"], wantsTripod:false, wantsND:true, wantsMic:false, tips:["Collect a mix of wide, medium, close-up, and detail shots for editing flexibility.","Let color and white balance choices match the song's mood \u2014 rules are meant to bend here.","A slider or gimbal move timed to the beat elevates even a simple shot."], summary:"Shoot more variety than feels necessary and let the edit and the music dictate the final look." }
  };

  var GENERIC_PHOTO = { aperture:"f/4 \u2013 f/5.6", shutter:"1/250s", iso:"Auto (100\u2013800)", wb:"Auto", focus:"Single-shot AF, center point", note:"A safe, versatile starting point \u2014 nudge it once you see how the shot looks.", idealLens:["Standard zoom (24-70mm)"], wantsTripod:false, wantsND:false, tips:["Check your histogram after the first frame and adjust from there.","Recompose after focusing if your subject isn't centered."], summary:"A balanced, general-purpose starting point for this shot." };
  var GENERIC_VIDEO = { aperture:"f/2.8 \u2013 f/4", shutter:"1/50s (180-degree rule at 24fps)", iso:"As needed", fps:"24fps", wb:"Auto", focus:"AF-C, smooth", note:"A safe, cinematic-leaning starting point.", idealLens:["Standard zoom (24-70mm)"], wantsTripod:false, wantsND:false, wantsMic:false, tips:["Keep white balance locked once you find a look you like.","Get a few extra seconds of handle at the start and end of each clip."], summary:"A balanced, general-purpose starting point for this shot." };

  var COMPOSITION_TIPS_BY_SCENE = {
    "Portrait":"Leave a little space in the direction your subject is looking.",
    "Landscape":"Put the horizon on the upper or lower third, not dead center.",
    "Wildlife":"Leave room in the frame for the animal to move into.",
    "Sports / action":"Frame a little loose \u2014 fast subjects drift out of tight crops.",
              
